// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/": {
            "get": {
                "description": "Responds with the test answer as JSON.",
                "tags": [
                    "Server"
                ],
                "summary": "Get Test",
                "responses": {}
            }
        },
        "/api/cart/addToCart": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Add Product To Cart",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Add To Cart",
                "parameters": [
                    {
                        "description": "Cart Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AddToCartRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/customer/register": {
            "post": {
                "description": "Register Customer with name and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "summary": "Register Customer",
                "parameters": [
                    {
                        "description": "Customer",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CustomerRegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Customer created successfully"
                    }
                }
            }
        },
        "/api/product/getAllCategory": {
            "get": {
                "description": "Get all product categories",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "Get All Categories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ProductCategoryResponse"
                        }
                    }
                }
            }
        },
        "/api/product/getPopProducts": {
            "get": {
                "description": "Get all Pop Products",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "Get All Pop Products",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.PopProductsResponse"
                        }
                    }
                }
            }
        },
        "/api/product/getProduct": {
            "post": {
                "description": "Get Product by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "Get Product",
                "parameters": [
                    {
                        "description": "Product Id",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.ProductRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ProductResponse"
                        }
                    }
                }
            }
        },
        "/api/product/getProductsByCategory": {
            "post": {
                "description": "Get products by category name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "Get All Products By Category",
                "parameters": [
                    {
                        "description": "Category Name",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.ProductsByCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ProductsByCategoryResponse"
                        }
                    }
                }
            }
        },
        "/api/profile/info": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get Profile Info by customer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Get Profile Info",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/cart/getCart": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get Products from Cart by customer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Get Cart",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/customer/login": {
            "post": {
                "description": "Login Customer with name and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "summary": "Login Customer",
                "parameters": [
                    {
                        "description": "Customer",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CustomerLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Customer logged in successfully",
                        "schema": {
                            "$ref": "#/definitions/response.TokenResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ProductDescription": {
            "type": "object",
            "properties": {
                "additional_info": {
                    "type": "string"
                },
                "color": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "material": {
                    "type": "string"
                }
            }
        },
        "request.AddToCartRequest": {
            "type": "object",
            "properties": {
                "productId": {
                    "type": "integer"
                },
                "size": {
                    "type": "string"
                }
            }
        },
        "request.CustomerLoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "request.CustomerRegisterRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "request.ProductRequest": {
            "type": "object",
            "properties": {
                "productId": {
                    "type": "integer"
                }
            }
        },
        "request.ProductsByCategoryRequest": {
            "type": "object",
            "properties": {
                "categoryName": {
                    "type": "string"
                }
            }
        },
        "response.Category": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "response.PopProductsResponse": {
            "type": "object",
            "properties": {
                "products": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.ProductResponsePart"
                    }
                }
            }
        },
        "response.ProductCategoryResponse": {
            "type": "object",
            "properties": {
                "categories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.Category"
                    }
                }
            }
        },
        "response.ProductResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "$ref": "#/definitions/models.ProductDescription"
                },
                "image_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "string"
                },
                "productId": {
                    "type": "integer"
                },
                "sizes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "response.ProductResponsePart": {
            "type": "object",
            "properties": {
                "description_info": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "string"
                },
                "productId": {
                    "type": "integer"
                }
            }
        },
        "response.ProductsByCategoryResponse": {
            "type": "object",
            "properties": {
                "products": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.ProductResponsePart"
                    }
                }
            }
        },
        "response.TokenResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Bebeziansback",
	Description:      "This is a Bebeziansback",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
